"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { getTranslations } from "@/lib/supabase/data";
import { translations as fallbackTranslations } from "@/lib/world-cup-data";

type Language = "en" | "bn";

const translationOverrides: Record<Language, Record<string, string>> = {
  en: {
    title: "FUTHUB",
    subtitle: "World Cup 2026",
    allNationsSubtitle: "12 Groups, 48 Nations",
    groups: "Squads",
    hostNations: "Host Nations",
    allOtherNations: "Qualified Nations",
    fixtures: "Fixtures",
    table: "Table",
    stats: "Stats",
    player: "Player",
    all: "All",
    players: "Players",
    position: "Position",
    club: "Club",
    age: "Age",
    height: "Height",
    weight: "Weight",
    strongFoot: "Preferred Foot",
    marketValue: "Market Value",
    squadValue: "Squad Value",
    back: "Back",
    searchPlaceholder: "Search nations...",
    goalkeeper: "Goalkeeper",
    defender: "Defender",
    midfielder: "Midfielder",
    forward: "Forward",
    left: "Left",
    right: "Right",
    both: "Both",
    language: "Language",
    hosted: "Hosted by",
    jerseyColors: "Jersey Colors",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    untilWorldCup: "UNTIL WORLD CUP 2026",
    matchFixtures: "Match Fixtures",
    schedule: "FIFA World Cup 2026 Schedule",
    searchMatches: "Search matches, teams, or stadiums...",
    groupStage: "Group Stage",
    roundOf32: "ROUND OF 32",
    roundOf16: "ROUND OF 16",
    quarterFinals: "QUARTER-FINALS",
    semiFinals: "SEMI-FINALS",
    bronzeFinal: "BRONZE FINAL",
    final: "FINAL",
    matchday: "Matchday",
    matches: "Matches",
    vs: "VS",
    groupTable: "Group Table",
    groupTableDescription: "Wins, draws, losses, goals, goal difference, and points by group",
    knockoutStage: "Knockout Stage",
    bestThirdPlaceTeams: "Best Third-Place Teams",
    bestThirdPlaceDescription: "Top 8 third-place teams advance to the knockout stage",
    nation: "Nation",
    playedShort: "P",
    winsShort: "W",
    drawsShort: "D",
    lossesShort: "L",
    goalsForShort: "GF",
    goalsAgainstShort: "GA",
    goalDifferenceShort: "GD",
    pointsShort: "PTS",
    goals: "Goals",
    assists: "Assists",
    goalsAssists: "Goals + Assists (G/A)",
    minutesPlayed: "Minutes Played",
    distanceCoveredMeters: "Distance Covered (m)",
    averageRating: "Average Rating",
    yellowCards: "Yellow Cards",
    redCards: "Red Cards",
    offsides: "Offsides",
    loadingLatestStats: "Loading latest stats...",
    loadingUpdatedFixtures: "Loading updated fixture data...",
    loadingLatestStandings: "Loading latest standings",
    noDataAvailableYet: "No data available yet.",
    rating: "Rating",
    distanceMetersShort: "Distance (m)",
    knockoutRoundLabel: "Match",
    winnerMatch: "Winner Match",
    loserSemiFinal: "Loser Semi-Final",
    tbd: "TBD",
    fullTimeShort: "FT",
    halfTimeShort: "HT",
    extraTimeHalfTimeShort: "ET HT",
    extraTimeShort: "ET",
    penaltiesShort: "PEN",
    liveShort: "LIVE",
    scheduled: "Scheduled",
    fullTime: "Full-time",
    halfTime: "Half-time",
    halfTimeTimer: "Half Time",
    extraTimeHalfTime: "Extra-time half-time",
    extraTimeHalfTimeTimer: "ET Half Time",
    endOf90Minutes: "End of 90 minutes",
    penaltyShootout: "Penalty shoot-out",
    extraTimeFirstHalf: "Extra-time 1st half",
    extraTimeSecondHalf: "Extra-time 2nd half",
    firstHalf: "First Half",
    secondHalf: "Second Half",
    penaltyShootoutShort: "Pens",
    matchHighlights: "MATCH HIGHLIGHTS",
    matchStats: "Match Stats",
    lineups: "Line-ups",
    noGoals: "No goals",
    playerOn: "Player on",
    playerOff: "Player off",
    playerInShort: "IN",
    playerOutShort: "OUT",
    unknownPlayer: "Unknown player",
    unknownScorer: "Unknown scorer",
    ownGoalShort: "OG",
    penaltyShort: "P",
    assist: "assist",
    possession: "Possession",
    expectedGoals: "Expected Goals (xG)",
    shots: "Shots",
    shotsOnTarget: "Shots On Target",
    passes: "Passes",
    passingAccuracy: "Passing Accuracy",
    corners: "Corners",
    fouls: "Fouls",
    postponed: "Postponed",
    cancelled: "Cancelled",
    suspended: "Suspended",
    interrupted: "Interrupted",
  },
  bn: {
    title: "ফিফহাব ২৬",
    subtitle: "বিশ্বকাপ ২০২৬",
    allNationsSubtitle: "১২টি গ্রুপ, ৪৮টি দেশ",
    groups: "দেশসমূহ",
    hostNations: "আয়োজক দেশ",
    allOtherNations: "অন্যান্য দেশ",
    fixtures: "ফিক্সচার",
    table: "টেবিল",
    stats: "পরিসংখ্যান",
    player: "খেলোয়াড়",
    all: "সব",
    players: "খেলোয়াড়",
    position: "পজিশন",
    club: "ক্লাব",
    height: "উচ্চতা",
    weight: "ওজন",
    strongFoot: "শক্তিশালী পা",
    marketValue: "বাজার মূল্য",
    squadValue: "স্কোয়াড মূল্য",
    back: "ফিরে যান",
    searchPlaceholder: "দেশ খুঁজুন...",
    goalkeeper: "গোলরক্ষক",
    defender: "ডিফেন্ডার",
    midfielder: "মিডফিল্ডার",
    forward: "ফরোয়ার্ড",
    left: "বাম",
    right: "ডান",
    both: "উভয়",
    language: "ভাষা",
    hosted: "আয়োজক",
    jerseyColors: "জার্সির রং",
    days: "দিন",
    hours: "ঘণ্টা",
    minutes: "মিনিট",
    seconds: "সেকেন্ড",
    untilWorldCup: "বিশ্বকাপ ২০২৬ পর্যন্ত",
    matchFixtures: "ম্যাচ ফিক্সচার",
    schedule: "ফিফা বিশ্বকাপ ২০২৬ সূচি",
    searchMatches: "ম্যাচ, দল বা স্টেডিয়াম খুঁজুন...",
    groupStage: "গ্রুপ পর্ব",
    roundOf32: "৩২ দলের পর্ব",
    roundOf16: "১৬ দলের পর্ব",
    quarterFinals: "কোয়ার্টার-ফাইনাল",
    semiFinals: "সেমি-ফাইনাল",
    bronzeFinal: "ব্রোঞ্জ ফাইনাল",
    final: "ফাইনাল",
    matchday: "ম্যাচডে",
    matches: "ম্যাচ",
    vs: "বনাম",
    clickNationToViewSquad: "স্কোয়াড দেখতে একটি দেশ নির্বাচন করুন",
    groupTable: "গ্রুপ টেবিল",
    groupTableDescription: "জয়, ড্র, হার, গোল, গোল ব্যবধান ও পয়েন্ট",
    knockoutStage: "নকআউট পর্ব",
    bestThirdPlaceTeams: "সেরা তৃতীয় স্থানের দল",
    bestThirdPlaceDescription: "সেরা ৮টি তৃতীয় স্থানের দল নকআউট পর্বে উঠবে",
    nation: "দেশ",
    playedShort: "খে",
    winsShort: "জ",
    drawsShort: "ড্র",
    lossesShort: "হা",
    goalsForShort: "পগ",
    goalsAgainstShort: "বিগ",
    goalDifferenceShort: "ব্যব",
    pointsShort: "পয়েন্ট",
    goals: "গোল",
    assists: "অ্যাসিস্ট",
    goalsAssists: "গোল + অ্যাসিস্ট (G/A)",
    minutesPlayed: "খেলা মিনিট",
    distanceCoveredMeters: "অতিক্রান্ত দূরত্ব (m)",
    averageRating: "গড় রেটিং",
    yellowCards: "হলুদ কার্ড",
    redCards: "লাল কার্ড",
    offsides: "অফসাইড",
    loadingLatestStats: "সর্বশেষ পরিসংখ্যান লোড হচ্ছে...",
    loadingUpdatedFixtures: "সর্বশেষ ম্যাচের তথ্য লোড হচ্ছে...",
    loadingLatestStandings: "সর্বশেষ পয়েন্ট তালিকা লোড হচ্ছে",
    noDataAvailableYet: "এখনও কোনো ডেটা নেই।",
    rating: "রেটিং",
    distanceMetersShort: "দূরত্ব (m)",
    knockoutRoundLabel: "ম্যাচ",
    winnerMatch: "ম্যাচ জয়ী",
    loserSemiFinal: "সেমি-ফাইনাল পরাজিত",
    tbd: "নির্ধারিত হয়নি",
    fullTimeShort: "ফিটি",
    halfTimeShort: "এইচটি",
    extraTimeHalfTimeShort: "ইটি এইচটি",
    extraTimeShort: "ইটি",
    penaltiesShort: "পেন",
    liveShort: "লাইভ",
    scheduled: "নির্ধারিত",
    fullTime: "ফুল-টাইম",
    halfTime: "হাফ-টাইম",
    halfTimeTimer: "হাফ টাইম",
    extraTimeHalfTime: "অতিরিক্ত সময়ের হাফ-টাইম",
    extraTimeHalfTimeTimer: "ইটি হাফ টাইম",
    endOf90Minutes: "৯০ মিনিট শেষ",
    penaltyShootout: "পেনাল্টি শুট-আউট",
    extraTimeFirstHalf: "অতিরিক্ত সময় ১ম হাফ",
    extraTimeSecondHalf: "অতিরিক্ত সময় ২য় হাফ",
    firstHalf: "প্রথম হাফ",
    secondHalf: "দ্বিতীয় হাফ",
    penaltyShootoutShort: "পেন",
    matchHighlights: "ম্যাচ হাইলাইটস",
    matchStats: "ম্যাচ স্ট্যাটস",
    lineups: "লাইন-আপ",
    noGoals: "কোনো গোল নেই",
    playerOn: "মাঠে নামা খেলোয়াড়",
    playerOff: "মাঠ ছাড়া খেলোয়াড়",
    playerInShort: "ইন",
    playerOutShort: "আউট",
    unknownPlayer: "অজানা খেলোয়াড়",
    unknownScorer: "অজানা গোলদাতা",
    ownGoalShort: "আত্মঘাতী",
    penaltyShort: "পেন",
    assist: "অ্যাসিস্ট",
    possession: "বল দখল",
    expectedGoals: "প্রত্যাশিত গোল (xG)",
    shots: "শট",
    shotsOnTarget: "লক্ষ্যে শট",
    passes: "পাস",
    passingAccuracy: "পাসের নির্ভুলতা",
    corners: "কর্নার",
    fouls: "ফাউল",
    postponed: "স্থগিত",
    cancelled: "বাতিল",
    suspended: "সাময়িক স্থগিত",
    interrupted: "বিঘ্নিত",
    argentina: "আর্জেন্টিনা",
    australia: "অস্ট্রেলিয়া",
    austria: "অস্ট্রিয়া",
    belgium: "বেলজিয়াম",
    bosniaherzegovina: "বসনিয়া ও হার্জেগোভিনা",
    brazil: "ব্রাজিল",
    capeverde: "কেপ ভার্দে",
    canada: "কানাডা",
    colombia: "কলম্বিয়া",
    croatia: "ক্রোয়েশিয়া",
    curacao: "কুরাসাও",
    czechia: "চেকিয়া",
    drcongo: "ডিআর কঙ্গো",
    ecuador: "ইকুয়েডর",
    egypt: "মিশর",
    england: "ইংল্যান্ড",
    france: "ফ্রান্স",
    germany: "জার্মানি",
    ghana: "ঘানা",
    haiti: "হাইতি",
    iran: "ইরান",
    iraq: "ইরাক",
    ivorycoast: "আইভরি কোস্ট",
    japan: "জাপান",
    jordan: "জর্ডান",
    mexico: "মেক্সিকো",
    morocco: "মরক্কো",
    netherlands: "নেদারল্যান্ডস",
    newzealand: "নিউজিল্যান্ড",
    norway: "নরওয়ে",
    panama: "পানামা",
    paraguay: "প্যারাগুয়ে",
    portugal: "পর্তুগাল",
    qatar: "কাতার",
    saudiarabia: "সৌদি আরব",
    scotland: "স্কটল্যান্ড",
    senegal: "সেনেগাল",
    southafrica: "দক্ষিণ আফ্রিকা",
    southkorea: "দক্ষিণ কোরিয়া",
    spain: "স্পেন",
    sweden: "সুইডেন",
    switzerland: "সুইজারল্যান্ড",
    tunisia: "তিউনিসিয়া",
    turkiye: "তুরস্ক",
    uruguay: "উরুগুয়ে",
    usa: "যুক্তরাষ্ট্র",
    uzbekistan: "উজবেকিস্তান",
    algeria: "আলজেরিয়া",
    friday: "শুক্রবার",
    saturday: "শনিবার",
    sunday: "রবিবার",
    monday: "সোমবার",
    tuesday: "মঙ্গলবার",
    wednesday: "বুধবার",
    thursday: "বৃহস্পতিবার",
    june: "জুন",
    july: "জুলাই",
    am: "এএম",
    pm: "পিএম",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [translations, setTranslations] = useState(fallbackTranslations);

  useEffect(() => {
    let isMounted = true;

    getTranslations()
      .then((supabaseTranslations) => {
        if (isMounted && Object.keys(supabaseTranslations).length > 0) {
          setTranslations(supabaseTranslations);
        }
      })
      .catch((error) => {
        console.error("Failed to load translations from Supabase:", error);
      });

    return () => {
      isMounted = false;
    };
  }, []);

  const t = (key: string): string => {
    const override = translationOverrides[language]?.[key];
    if (override) return override;

    return translations[language]?.[key] || translationOverrides.en[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export const languageNames: Record<Language, string> = {
  en: "English",
  bn: "বাংলা",
};
